INSERT INTO sqltask.companies (company_name) VALUES ('Google');
INSERT INTO sqltask.companies (company_name) VALUES ('Yandex');
INSERT INTO sqltask.companies (company_name) VALUES ('ALibaba');
INSERT INTO sqltask.companies (company_name) VALUES ('Amazon');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Bill', 'Gates', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Warren', 'Buffett', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Jeff', 'Bezos', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Amancio', 'Ortega', 'Spain');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Mark', 'Zuckerberg', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Carlos', 'Slim Helu', 'Mexico');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Larry', 'Ellison', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Charles', 'Koch', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('David', 'Koch', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Michael', 'Bloomberg', 'U.S.');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Bernard', 'Arnault', 'France');
INSERT INTO sqltask.customers (customer_firstName, customer_lastName, customer_address) VALUES ('Larry', 'Page', 'U.S.');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Ilya','Slysarenko', 'Java Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Denis','Grammakov', 'C Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Yaroslava','Gagen-Torn', 'C++ Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Anatoly','Karpenko', 'Pyton Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Youra','Karpenko', 'C# Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Youra','Krohmal', 'JavaScript Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Alexey','Martynov', 'Visual Basic .NET Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Anton','Dubrovin', 'PHP Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Alexander','Chayko', 'Delphi Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Sergey','Tarasov', 'Assembly Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Pasha','Fedorov', 'R Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Ilya','Orlov', 'MatLab Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Alexander','Gagen-Torn', 'Ruby Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Sergey','Karashevich', 'Go Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Sergey','Popov', 'Perl Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Alexey','Agadjanov', 'Scratch Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Marya','Belova', 'PL/SQL Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Anastasya','Akela', 'Objective-C Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Alexander','Melnikov', 'Swift Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Andrey','Sergeevich', 'Java Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Irina','Timkina', 'Java Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Ekaterina','Horina', 'C++ Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Denis','Elhov', 'C# Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Nikolay','Nimkevich', 'Java Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Max','Ebbert', 'Pyton Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Alexey','Pimanenko', 'Swift Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Olya','Pronevich', 'JavaScript Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Dmitry','Klochkov', 'Perl Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Artyom','Savenkov', 'Ruby Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('Nikita','Zadirushko', 'Go Developer');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Denis	','	Grammakov	', '	Java Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Nade	','	Syprycheva	', '	Go Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Vadim	','	Volkov	', '	Ruby Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Vadim	','	Grechishin	', '	Swift Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Alex	','	Burmistrova	', '	Pyton Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Chen	','	Lee	', '	C++ Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Fidel	','	Castro	', '	C# Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Alla	','	Magala	', '	JavaScript Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Artur	','	King	', '	Java Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Burushka	','	Horse	', '	Go Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Samanta	','	Alabama	', '	Ruby Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Kim	','	Karandash	', '	Swift Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Seka	','	Beka	', '	Pyton Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Boka	','	Voka	', '	C++ Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Semyon	','	Slepakov	', '	C# Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Gosha	','	Kosha	', '	JavaScript Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Kung	','	Lao	', '	Java Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Seva	','	Melnikov	', '	Java Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Alla	','	Malysheva	', '	Go Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Akella	','	Miss	', '	Ruby Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	Bred	','	Dead	', '	Swift Developer	');
INSERT INTO sqltask.developers (developer_firsName, developer_lastName, developer_specialty) VALUES ('	John	','	Dow	', '	Pyton Developer	');
INSERT INTO sqltask.projects (project_name) VALUES ('ScIO');
INSERT INTO sqltask.projects (project_name) VALUES ('Dash');
INSERT INTO sqltask.projects (project_name) VALUES ('PonoPlayer');
INSERT INTO sqltask.projects (project_name) VALUES ('Coolest Cooler');
INSERT INTO sqltask.projects (project_name) VALUES ('Ritot');
INSERT INTO sqltask.projects (project_name) VALUES ('Jibo');
INSERT INTO sqltask.projects (project_name) VALUES ('Skully AR-1');
INSERT INTO sqltask.projects (project_name) VALUES ('TouchPico');
INSERT INTO sqltask.projects (project_name) VALUES ('ZEN Thermostat');
INSERT INTO sqltask.projects (project_name) VALUES ('Music App');
INSERT INTO sqltask.projects (project_name) VALUES ('Robocorp');
INSERT INTO sqltask.projects (project_name) VALUES ('Scary Price');
INSERT INTO sqltask.skills (skills_name) VALUES ('JavaScript');
INSERT INTO sqltask.skills (skills_name) VALUES ('BigData');
INSERT INTO sqltask.skills (skills_name) VALUES ('MongoDB');
INSERT INTO sqltask.skills (skills_name) VALUES ('DevOps');
INSERT INTO sqltask.skills (skills_name) VALUES ('Java');
INSERT INTO sqltask.skills (skills_name) VALUES ('C#');
INSERT INTO sqltask.skills (skills_name) VALUES ('Ruby on Rails');
INSERT INTO sqltask.skills (skills_name) VALUES ('Python');
INSERT INTO sqltask.skills (skills_name) VALUES ('Django');
INSERT INTO sqltask.skills (skills_name) VALUES ('Node.js');
INSERT INTO sqltask.skills (skills_name) VALUES ('Scala');
INSERT INTO sqltask.skills (skills_name) VALUES ('Go');
INSERT INTO sqltask.skills (skills_name) VALUES ('AngularJS');
INSERT INTO sqltask.skills (skills_name) VALUES ('agile');
INSERT INTO sqltask.skills (skills_name) VALUES ('IaaS');
INSERT INTO sqltask.skills (skills_name) VALUES ('Go');
INSERT INTO sqltask.skills (skills_name) VALUES ('Amazon Web Services');
INSERT INTO sqltask.skills (skills_name) VALUES ('Google Cloud Compute');
INSERT INTO sqltask.skills (skills_name) VALUES ('API');
INSERT INTO sqltask.skills (skills_name) VALUES ('ASP.NET MVC');
INSERT INTO sqltask.skills (skills_name) VALUES ('XML');
INSERT INTO sqltask.skills (skills_name) VALUES ('AJAX');
INSERT INTO sqltask.skills (skills_name) VALUES ('SQL');
INSERT INTO sqltask.skills (skills_name) VALUES ('HTML');
INSERT INTO sqltask.skills (skills_name) VALUES ('CSS');
INSERT INTO sqltask.skills (skills_name) VALUES ('jQuery');
INSERT INTO sqltask.skills (skills_name) VALUES ('OOP');
INSERT INTO sqltask.teams (team_name) VALUES ('alpha');
INSERT INTO sqltask.teams (team_name) VALUES ('beta');
INSERT INTO sqltask.teams (team_name) VALUES ('gamma');
INSERT INTO sqltask.teams (team_name) VALUES ('delta');
INSERT INTO sqltask.teams (team_name) VALUES ('epsilon');
INSERT INTO sqltask.teams (team_name) VALUES ('zeta');
INSERT INTO sqltask.teams (team_name) VALUES ('eta');
INSERT INTO sqltask.teams (team_name) VALUES ('theta');
INSERT INTO sqltask.teams (team_name) VALUES ('iota');
INSERT INTO sqltask.teams (team_name) VALUES ('kappa');
INSERT INTO sqltask.teams (team_name) VALUES ('lambda');
INSERT INTO sqltask.teams (team_name) VALUES ('mu');
INSERT INTO sqltask.teams (team_name) VALUES ('nu');
INSERT INTO sqltask.teams (team_name) VALUES ('xi');
INSERT INTO sqltask.teams (team_name) VALUES ('omicron');
INSERT INTO sqltask.teams (team_name) VALUES ('pi');
INSERT INTO sqltask.teams (team_name) VALUES ('rho');
INSERT INTO sqltask.teams (team_name) VALUES ('sigma');
INSERT INTO sqltask.teams (team_name) VALUES ('tau');
INSERT INTO sqltask.teams (team_name) VALUES ('upsilon');
INSERT INTO sqltask.teams (team_name) VALUES ('phi');
INSERT INTO sqltask.teams (team_name) VALUES ('chi');
INSERT INTO sqltask.teams (team_name) VALUES ('psi');
INSERT INTO sqltask.teams (team_name) VALUES ('omega');

INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	1	', '	1	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	1	', '	2	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	2	', '	3	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	2	', '	4	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	3	', '	5	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	3	', '	6	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	4	', '	7	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	4	', '	8	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	5	', '	9	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	5	', '	10	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	6	', '	11	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	6	', '	12	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	7	', '	13	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	7	', '	14	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	8	', '	15	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	8	', '	16	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	9	', '	17	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	9	', '	18	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	10	', '	19	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	10	', '	20	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	11	', '	21	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	11	', '	22	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	12	', '	23	');
INSERT INTO `sqltask`.`teamsInTheProject` (`project_id`, `team_id`) VALUES ('	12	', '	24	');


